# Generated by Django 5.2.5 on 2025-09-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category_icons/')),
                ('exams', models.ManyToManyField(blank=True, related_name='categories', to='quiz.exam')),
            ],
        ),
    ]
